### PR TITLE
[FEATURE] Make default filenames and the current record configurable

### PR DESCRIPTION
**Pull request by linawolf**

### CODE REVIEW

**Review by alexander-nitsche — COMMENTED** [review]
There is a general question if the file names should be set implicitly or explicitly: My point of view on this is, that we should stick to explicitly naming the screenshot in the JSON file, as it gives the great benefit of having a direct link from a wrong screenshot file to the place in the JSON file which has to be adapted.

**Comment by linawolf** [comment]
@alexander-nitsche  I tried to cherry pick the commit from our meeting here.

**Review by alexander-nitsche — COMMENTED** [review]
> There is a general question if the file names should be set implicitly or explicitly: My point of view on this is, that we should stick to explicitly naming the screenshot in the JSON file, as it gives the great benefit of having a direct link from a wrong screenshot file to the place in the JSON file which has to be adapted.

I adapted the code so that
- the user can set default values for the TCA navigation specific params `table`, `pid` and `uid` individually
- the user can (and should) reset all default values at once when done with the TCA screenshots
- the final TCA table or record params get printed to terminal for re-check
- the user can navigate back from TCA pages to normal TYPO3 backend by new action `reloadBackend`

I removed the filename feature and want to confirm that i think it is better to have an explicit filename in each screenshot / code snippet entry in the screenshots.json.

**Comment by linawolf** [comment]
Ok for me, I cannot approve this PR as it is originally by me

**Review by alexander-nitsche — APPROVED** [review]

**Pull request merged**
